### ISSUE TITLE
CSGO theme sourcebans

### ISSUE THREAD

**Issue by ok5551** [sbpp/sourcebans-pp#1015]
Hi all,

The CSGO theme of sourcebans broke awhile ago. I was wondering if there could be support to fix and include with the TF2 theme? The CSGO one was made by the same person as the default TF2 theme included on sourcebans.

https://github.com/TF2Romania/SourceBans-CS-GO-Theme

Thanks.

Edit:
Theme looked like this and it supposedly worked on SB 1.6.4:
![image](https://github.com/user-attachments/assets/730b43ee-317c-4e9c-8124-35168598d5ed)

**Comment by Rushaway** [comment]
Hello,
It's up to the authors or anyone to fork this project and update it to make it compatible with sourcebanspp latest version.

According to the code used, it will be easier to just use the default theme as a base, grab the modified CSS and adjust it.
After you just need to bring back the display of different block. 
It's not an huge project because you already have a base to work on, but it might need few hours on it. :)
