### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by aldemaroc** [sbpp/sourcebans-pp#155]
Hi!

I'm trying to install sourcebans on a cPanel server, but i cannot pass the step 2 (MySQL details). It will just show a blank page after I enter the server details (http://prntscr.com/b7oxfa).

If I manually go to step 3, this is what i see: http://prntscr.com/b7oxne

MySQL is fully working, and PHP memory limit is 256MB. Tested PHP 5.5 and 5.6, same problem.

Do you have any ideia on how can I solve it?

**Comment by sarabveer** [comment]
Any php errors, can u enable displaying errors so I can see what PHP is erroring about.

**Comment by aldemaroc** [comment]
Hi!

I enabled error logging in php.ini., and there are no PHP errors (yes, i was shocked too). If you want to take a look, I can send you cpanel details to your email.

**Comment by kalkafox** [comment]
Hi! I'm having this same issue as well.

PHP errors that output on my cPanel server are non-existant. However, I installed an Apache/PHP server on a different VM with the same MySQL module, and it worked. There may be some kind of conflict going on with SourceBans++ and cPanel, but I'm not too sure.

**Comment by sarabveer** [comment]
This issue has been around for 2 years now. Its a problem with your config.

**Comment by kalkafox** [comment]
Could you be more elaborate? Is there a certain PHP setting that needs to be set or am I missing a certain module?

**Comment by sarabveer** [comment]
See, I cant. I have never personally experienced this issue. I used Apache and NGINX, PHP and HHVM, MySQL and MariaDB, never got this blank screen issue.

Neither have I gotten any log file, error message, or any clue why this is happening.

I cant do much.

The reason I say it is a problem with your config is because whenever people do a fresh install of their stack, it worked perfectly.

Just like someone here just stated it worked fine in a VM.

**Comment by aldemaroc** [comment]
This is a issue that happens in a fresh install of cPanel, with any PHP version. If you want, I can host a test version for you (for life, if you need some place to test your releases), this way you can test what's going wrong.

**Comment by sarabveer** [comment]
It has to be cPanel doing something. What PHP version are you using? Or have used.

**Comment by aldemaroc** [comment]
I tested stock and self-compiled 5.5 and 5.6, same problem. Increased PHP memory limit, safe mod off and still same problem. I already gave up and installed it on a VPS, but cPanel is the most used web hosting panel, and lots of user will expect this bug.

**Comment by sarabveer** [comment]
Only ~6 people have reported this problem.

**Comment by jrod9k1** [comment]
After some playing about we've fixed the issue. It turned out that by default cPanel does not enable the MySQLi extension. If you have root access to the server you can run easyapache and recompile with the PHP extension "MySQL Improved" enabled.

![mysqli](http://img.jrod.mx/2016/06/bmo_%E2%80%93_WebHost_Manager_-_Google_Chrome_2016-06-12_14-33-51.png)

I'd also recommend MySQLi be added to the list of requirements in the readme to prevent future issues like this.

Props to @mild-prowler for finding this issue.

**Comment by sarabveer** [comment]
The PHP MySQL has been deprecated in PHP 5.5+, and has been removed in PHP7.

MySQLi is the standard and I expect everyone to have extension.
