### ISSUE TITLE
Admin does not work

### ISSUE THREAD

**Issue by coolmans** [sbpp/sourcebans-pp#220]
Admin does not work

![default](https://cloud.githubusercontent.com/assets/14921798/22801139/843a38ae-ef2d-11e6-948d-8c11805194eb.jpg)

**Comment by Technoblazed** [comment]
"Admin does not work"

**Comment by Groruk** [comment]
Everything works fine and as intended, because the standalone login was disabled since SourceBans++ 1.5.5. This was done to prevent people from using a super outdated sha1 encryption with a default salt. If you want to enabled standalone login connect to your mysql database and in the sb_settings table you will find config.enablesteamlogin set this to 1 and you have your standalone login and a big security flaw.

**Comment by Groruk** [comment]
Also next time you want to open a issue on github to just write 'admin does not work' ...
![11d67377311cf1515b41e5b0fa7baa1b](https://cloud.githubusercontent.com/assets/5796460/22804991/cacf608a-ef1b-11e6-9b5f-7811397aa962.jpg)

**Comment by coolmans** [comment]
Groruk, thank you friend, helped me, for my safety, do not worry, I have a hard protection through the iptables, the access to the admin center have only me.
