### ISSUE TITLE
Database Password Bug with Solution

### ISSUE THREAD

**Issue by brhndursun** [sbpp/sourcebans-pp#235]
In the config file "config.php" where you set up your database password, if you use some characters (like "#") you will get a blank page.

It happens in init.php at line 128

`$GLOBALS['db'] = ADONewConnection("mysqli://".DB_USER.':'.DB_PASS.'@'.DB_HOST.':'.DB_PORT .'/'.DB_NAME);`

it will try to connect to the database, if it fails, the page dies whith no error.
`if( !is_object($GLOBALS['db']) )
                die('');  `
Solution: just urlencode the DB_PASS
`$GLOBALS['db'] = ADONewConnection("mysqli://".DB_USER.':'.urlencode(DB_PASS).'@'.DB_HOST.':'.DB_PORT.'/'.DB_NAME);  `

Original Post by lugui : https://forums.alliedmods.net/showthread.php?t=294461

**Comment by Technoblazed** [comment]
\# cancels out the remainder of the line, why the hell would you use a # in a password

**Comment by eNNercY1337** [comment]
Where is the issue with using a # in the PW?
Not so uncommon lol

**Comment by Groruk** [comment]
@Technoblazed not in this case since [config.php](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/config.php.template) is using [single quoted strings](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.single) they don't interpret special characters like #.  I will take a look into this and push a commit with the changes later.

**Comment by Groruk** [comment]
done
