### ISSUE TITLE
AJAX Call Failed ! SourceBans++ 1.6.0-git0

### ISSUE THREAD

**Issue by rzrhome** [sbpp/sourcebans-pp#261]
Any Idea ? The Problem is only by Port 27015 all other Ports works perfectly. ( on Site http://xx.xxxx.xx/index.php?p=admin&c=servers )

`Error: the XML response that was returned from the server is invalid. Received: 0/20]]>]]>aim_deagle8k_go$('mapimg_1').setProperty('src', 'images/maps/aim_deagle8k_go.jpg').setProperty('alt', 'aim_deagle8k_go').setProperty('title', 'aim_deagle8k_go');$('sinfo_1').setStyle('display', 'none');$('noplayer_1').setStyle('display', 'block');$('serverwindow_1').setStyle('height', '64px');$('dialog-control').setStyle('display', 'block');$('dialog-placement').setStyle('display', 'none');`

also

( on Site http://xx.xxxx.xx/index.php?p=admin&c=admins )

`Error: the XML response that was returned from the server is invalid. Received:`

Version:
SourceBans++ 1.6.0-git0

WebServer:
Apache2
PHP 7.1
MYSQL 5.7

Link: http://sb.csmesh.de/

**Comment by SugarD-x** [comment]
I'm also getting this in the latest version of MySQL8 server when trying to add a server through the Sourcebans++ web interface. It still adds the server successfully despite the error message. I just have to refresh the page to display it. Not sure if it is related or not. I'm running PHP 7.2.8, if that helps. (Maybe it is a PHP 7.x issue?)

**Comment by Groruk** [comment]
This one is hard, just because it's not reproducible (at least not for me).

[Here](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/sb-callback.php#L1250) is the exact line where the error should origin from (at lest if I can trust the output given in the issue here).
1) It could be an issue with the [trunc()](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L104-L107) function which I have refactored in #528 to remove the unused code within the function.

2) Or it could be some bug in the escape functions of the XAJAX library (if this would be the case we would probably see a lot more of these issues popping up)

Since this issue is so wildly inconsistent I will close this issue until somebody finds a way to reliably reproduce it.

**Comment by CrazyHackGUT** [comment]
#528 can't fix XAJAX error.
This is hard to explain. For understanding reasons, you need look in XAJAX Response builder.
It’s really simple bug. XAJAX build response manually, with string concatenation.
https://github.com/sbpp/sourcebans-pp/blob/39301095a13dea67fab939e5fb69ef6c3501daba/web/includes/xajaxResponse.inc.php#L702-L754
And sometimes, he fails when response contains special characters (like emojis and etc.). But not always.
