### ISSUE TITLE
Login don´t work after Updater 1.6.0

### ISSUE THREAD

**Issue by rzrhome** [sbpp/sourcebans-pp#262]
After use the Updater Folder from "SourceBans++ 1.6.0-git0" i can´t login anymore.

**Comment by Groruk** [comment]
Ok maybe give some context if you have an issue, like

* Which login did you use Standalone / Steam
* What is your current MySQL version
* What is your current PHP version
* From which version did you upgrade
* Do you have a SB_NEW_SALT in your config.php and is it empty?
* Also in your config you should have a DB_CHARSET tell me if this is set to utf8 or utf8mb4
* Go into your SourceBans database and in the table sb_admins you should find your hashed password. Tell me if the password looks like this $5${Your SB_NEW_SALT}${hashed password} or is just a random string of numbers and characters


>In the future if you have an issue with open source software and you want it resolved you should really try and give some basic info so people can help you.

**Comment by rzrhome** [comment]
1. Standalone
2. 5.7
3. 7.1
4. 1.6.0.0 to 1.6.0.1 (601)
5. SB_NEW_SALT is in config
6. DB_CHARSET is utf8mb4_unicode_ci
7. looks like $5$3777xxxxWsduU$jBJYB/uF70fXm3Usbxxxxxuq4gDxVwtlGOS3

**Comment by Groruk** [comment]
Since your password hash got updated to the new hash format you should be able to login.
(Normally the password gets updated on an [successful login](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/CUserManager.php#L215))

- Do you get an error message saying "username or password is wrong" or do you get redirected and just not be logged in?
- Is the salt in your password hash (`$5$3777xxxxWsduU`$jBJYB/uF70fXm3Usbxxxxxuq4gDxVwtlGOS3) the same as in SB_NEW_SALT?
- Have you tried logging in with steam to see if that works?
- Maybe clear the cookies for your SourceBans++ page and see if you still have the problem

**Comment by rzrhome** [comment]
*update* i have reinstall all now. if comes a update i will check it again for you.
