### ISSUE TITLE
[sourcecomms.smx] Saving punishment

### ISSUE THREAD

**Issue by IzuiSP** [sbpp/sourcebans-pp#263]
`[sourcecomms.smx] Saving punishment for STEAM_X:X:XXXXXXX into queue`
`[sourcecomms.smx] Saving punishment for STEAM_X:X:XXXXXXX into queue`
`[sourcecomms.smx] Saving punishment for STEAM_X:X:XXXXXXX into queue`
`[sourcecomms.smx] Saving punishment for STEAM_X:X:XXXXXXX into queue`
`[sourcecomms.smx] Saving punishment for STEAM_X:X:XXXXXXX into queue`

10 000 results of gag and mute 

Should I clear the list ?

**Comment by Groruk** [comment]
It's perfectly fine to clear your logs, but if you want to know why you get this issue here is an explanation:

So the log entry is created by [SourceComms.smx](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp) so let's take a look inside.
If we search for "Saving punishment for" we can find [this](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L2562) line in the function [InsertTempBlock](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L2560) which is called from 2 positions:

1. From [this](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L2929) if-else structure where it gets called when [DB_Connect](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L2929) fails and returns false (aka when it cant connect to your specified database).
2. From [this](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L1273) if-else structure when [DB_Conn_Lost](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L1997) returns true (aka it loses the connection to your database while operating).

We now know that the function is called when there is no connection to the database or the connection is lost so what can we do to fix this? Well, simple **check your database connection** then the message shouldn't pop up in the logs anymore.

**Comment by IzuiSP** [comment]
Okay thx man.

Btw where can I found the SourceBans 1.5.2F-dev ?

**Comment by Technoblazed** [comment]
That's a ridiculously outdated version of sourcebans, why would you even want that?

**Comment by IzuiSP** [comment]
I saw a community open since 10 years have that version

**Comment by IzuiSP** [comment]
can someone tell me where to download ?
I found : https://github.com/sbpp/sourcebans-pp/releases
But not the 1.5.2F-dev

**Comment by Technoblazed** [comment]
Pretty sure 1.5.2 was the old sourcebans, developed by the old team. That version has so many security exploits, I'd severely recommend just using this one.

**Comment by Groruk** [comment]
There is no 1.5.2F-dev version anymore. The `-dev` means it's the current development version that isn't finished for release yet (so 1.5.2F-dev got released as 1.5.2F). The current dev version would be 1.6.0-dev
