### ISSUE TITLE
Error 1115

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#273]
Fatal error: mysqli error: [1115: Unknown character set: 'utf8mb4;'] in EXECUTE("SET NAMES utf8mb4;") in /storage/h12/987/1511987/public_html/includes/adodb/adodb-errorhandler.inc.php on line 79

## My Environment

* Version used: SourceBans++ Stable Build ver 1.6
* PHP and MySQL version: PHP 7.1 (not sure about MySQL)
* Operating System and version: Game Server is running on Windows 10, not sure about Website.
* Link to your project: elementedservers.000webhostapp.com (Yes I'm a free hosting scrub)
* Link to gist with phpinfo() output: not sure

**Comment by InvexByte** [comment]
The character set 'utf8mb4' was introduced in MySQL 5.5.3.
Chances are you are using an older version than this.

**Comment by Bara** [comment]
And MySQL 5.5.3 was 2010 released. It's a bit old or?

**Comment by Groruk** [comment]
Go to your config.php and change `DB_CHARSET` from `utf8mb4` to `utf8` and it should work.
Also just a quick side-note that most 'free' hosting services will not support SourceBans++ completely, because most of them block tcp/udp ports which need to be used for communication between the SourceBans++ webpanel and your gameserver.

**Comment by ghost** [comment]
I'm still having a issue

Fatal error: mysqli error: [1115: Unknown character set: 'utf8;'] in EXECUTE("SET NAMES utf8;") in /storage/h12/987/1511987/public_html/includes/adodb/adodb-errorhandler.inc.php on line 79

**Comment by CrazyHackGUT** [comment]
Your MySQL server don't know about encoding `utf8`.
