### ISSUE TITLE
[REQUEST] Ban by game server

### ISSUE THREAD

**Issue by GoRiLliAz** [sbpp/sourcebans-pp#312]
## Expected Behavior

Hello,
We are several team on the same dedicated machine, we do not share the ban.
You should add the ability to choose whether a server uses only the bans linked to are IDs or if it uses all the bans of all the servers.

**Comment by Groruk** [comment]
@GoRiLliAz  Please use the Issue template, which can be found here: https://github.com/sbpp/sourcebans-pp/blob/v1.x/.github/ISSUE_TEMPLATE.md to give us a more clear understanding of what your problem is.

***

This issue will be closed in one week, after no replies or the issue template hasn't been followed.
