### ISSUE TITLE
Feature request; Web API instead of remote mysql

### ISSUE THREAD

**Issue by distobj** [sbpp/sourcebans-pp#336]
I just tried to install sbpp, and got to the end of the install where the databases.cfg file snippet was presented, including the mysql remote host info. I have a shared hosting package with 1and1 and was pretty sure that they didn't allow remote access. Sure enough, that was the case.

Rather than using mysql over the internet, I suggest a Web interface ("REST API" if you prefer - I do not :). It would reduce the requirements on the installation environment, making it usable in cheaper hosting environments like mine. There are also other architectural improvements that this change would bring (decoupling of plugin code and database schema, for example), but it's unclear to me of the value to the project at this time.

Thanks.

**Comment by Groruk** [comment]
**This will not happen.** 
The plugin and the web panel of SourceBans++ are separated parts (and we want to keep it this way). 
The web panel is here to give the end user a simpler interface to work with SB++ and to some extend to add new functionality to the plugin. 
The plugin shouldn't be dependent on the web panel (in theory you can run the plugin without the web panel) but on the MySQL database. 
Almost all bigger plugins need to rely on a MySQL database to access data over multiple game server why be the odd ones out and depend on a web API instead.

It sounds like you should overthink your server setup or talk to your hoster maybe they can help you.
You're also free to fork SB++ and build your own API for this (we won't since we see no real improvement).

**Comment by CrazyHackGUT** [comment]
If you do not need an admin panel in the web panel and you know russian language, you can look OctoBans.
OctoBans - Lightweight simple ban and comms system with RESTful API.
You can find web [here](http://hlmod.ru/resources/489/), plugin [here](http://hlmod.ru/resources/216/).
