### ISSUE TITLE
Adding admins requires password despite no web group permissions

### ISSUE THREAD

**Issue by geominorai** [sbpp/sourcebans-pp#350]
Adding new admins while setting the Web Admin Group to No Permissions still requires setting a password.  This did not used to happen until updating to the latest build a few months back.

## Expected Behavior
Adding a new admin without web admin permissions should not demand a password to be set.

## Current Behavior
Adding a new admin now always requires a password even if they do not have access to login to SourceBans web panel in the first place.

## Steps to Reproduce
1. Add a new admin through the admin panel
2. Leave the Admin Password fields blank
3. Click Add Admin

## Context
We have a lot of staff and donors on our servers that we add on a regular basis and having to set a random password is inconvenient and the change in the page's behavior is unexpected.

## Your Environment
* Version used: 1.6.3-git551

**Comment by rumblefrog** [comment]
It's not a bug and it's intended, but surely it can be enhanced. For now you can let them sign in via Steam oAuth.

**Comment by Groruk** [comment]
> Adding
 a new admin now always requires a password even if they do not have access to login to SourceBans web panel in the first place.

**First of all**: Everybody that has an account for your sourcebans web panel can login into that web panel, even if they don't have permission.

**So why is that automatic password generating function being removed?**
Simple. Many users had configuration problems with `random_compat` (the polyfill lib we needed to use when most users had PHP 5.6 installed). Because most people can't use google or a search function we had 15-20 people per week asking for support with `random_compat`! So to make our lives easier we removed the feature altogether and switched to session based logins to utilize PHP's internal function for hashing/salting.

**Will there be an alternative?**
Yes. PHP 7 has internal polyfill functions we will use for automatically generated passwords in the future.
All users below PHP 7 will not get this feature. (Maybe people will start upgrading to PHP 7)

**Comment by geominorai** [comment]
It's been about 9 months now.  Do we still have the predicament of users not upgrading to PHP7?

Can we do a version or dependency check and have this work for those who do have PHP7?

**Comment by Groruk** [comment]
After thinking about this and other planned features (mostly around the session based login that needs a rewrite) I would like to use `OpenSSL` for the cryptography and random number generation.
But to avoid the same issues as the requirement for GMP we need to first adress #443

**Comment by geominorai** [comment]
I think we would also need to check for new library requirements in updater too, or show some warning after updating about critical features being unavailable.

**Comment by Groruk** [comment]
Currently the updater is not designed to do anything besides updating the config or the database (structure). I will probably just add a new module to the updater that checks for all needed extensions

**Comment by CrazyHackGUT** [comment]
> It's not a bug

I disagree. Original SourceBans allow add admin without password if he don't have any web permissions.

**Comment by rumblefrog** [comment]
And this is the original?

**Comment by Groruk** [comment]
> I disagree. Original SourceBans allow add admin without password if he don't have any web permissions.

Doesn't change the fact that this was one of the dumbest design choices concerning security, right after the static `SourceBans` salt for every, single, installation.

**Comment by CrazyHackGUT** [comment]
> And this is the original?

No. But this "feature" with unavailable action "Create admin without web permissions and password" - bug.
Also SB++ 1.5.4.7 allows creating admin without password and web flags. So i think this is a bug.
