### ISSUE TITLE
Doubt with MOD/COUNTRY

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#383]
I did the installation and everything was fine.

But I have the following problem: https://prnt.sc/hvpapn
![sem titulo](https://user-images.githubusercontent.com/32937653/34540397-89cc8ec6-f0bb-11e7-88ed-aa72902282ab.png)

As you can see the countries flag is not displayed, how can I correct?

**Comment by rumblefrog** [comment]
Does `br.jpg` exist in `/images/country/br.jpg`?

**Comment by Groruk** [comment]
If he had filled out the issue template, we would have the link to his [SBPP installation](https://www.zkservidores.com/sourcebans/). Judging by that the site still uses `br.gif` files which could indicate that either there are still cached smarty files that contain `br.gif` instead of `br.png` because the home tab loads the `br.png` but banlist doesn't.

**Comment by crashzk** [comment]
@RumbleFrog yes the br.jpg image exists, I checked.

@Groruk you do not have any .gif in the country images folder.

Image is in .jpg.

**Comment by crashzk** [comment]
Corrected, I understood what @Groruk  meant, thank you both.
