### ISSUE TITLE
sm_voteban

### ISSUE THREAD

**Issue by Allower** [sbpp/sourcebans-pp#467]
What are the steps to reproduce this issue?
-------------------------------------------
1. sm_admin
2. Voting Commands
3. Start Vote for Ban a player
4. Press Yes for sucessful ban

What happens?
-------------
Player banned, but not by SourceBans (all versions since sb 1.4.9 to sb++ 1.6.3)
Player banned like standart banid fuction on source engine

What were you expecting to happen?
----------------------------------
SourceBans must list this ban to database. Because sm_votemute/votegag/votesilnce writting to databases without any problems.

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------
I don't know why no everyone not try to use sm_voteban and report this bug early.
Beacause this is not a feature, i think it's really bug. You all guys can test this it's self.
And read this thread on AM:
https://forums.alliedmods.net/showthread.php?t=197790
But if you download this plugin and try to voteban someone, your ban dublicates 20 or 30 times xD

Screenshot below:

![](https://i.imgur.com/I9d1DeO.jpg)

What versions of software are you using?
----------------------------------------
**Operating System: all OS versions**
**SourceBans++ Version: all sourcebans versions**
**SourceMod Version: all sourcemod versions**
**MetaMod Version: all metamod versions**

**Comment by rumblefrog** [comment]
```
Operating System: all OS versions
SourceBans++ Version: all sourcebans versions
SourceMod Version: all sourcemod versions
MetaMod Version: all metamod versions
```

This is not helpful at all.

> Player banned, but not by SourceBans (all versions since sb 1.4.9 to sb++ 1.6.3)

All voting commands proxies through SM's voting system and calls their respective Sourcemod func, **NOT** SourceBans++'s.

Because you did not attach proper versioning info, I'm unable to determine if that uses the proper include file, with the new natives, which I doubt it's as it's from 2012.

> And read this thread on AM:
> https://forums.alliedmods.net/showthread.php?t=197790
> But if you download this plugin and try to voteban someone, your ban dublicates 20 or 30 times xD

You cannot directly listen for `OnBanClient` as SourceBans, and SourceBans++ will call it again, causing an infinite loop.

> I don't know why no everyone not try to use sm_voteban and report this bug early.
> Beacause this is not a feature, i think it's really bug.

Voting was never included in SB. Therefore it's **NOT** a bug; if you wish to incorporate these, you must modify the function calls
