### ISSUE TITLE
Admin STEAM ID

### ISSUE THREAD

**Issue by ByKyTa** [sbpp/sourcebans-pp#484]
Admin STEAM ID
I set STEAM_1:1xx auto change STEAM_0:1xxx

**Comment by Groruk** [comment]
The code is designed to do that https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/SteamID/SteamID.php#L44, because `STEAM_0` is used on the Steam website (for api requests, login, etc)
and `STEAM_1` is used ingame by a small amount of games.

Also don't open an issue without having a real issue or filling out the issue template.
