### ISSUE TITLE
Display message when SteamID login fails

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#487]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------

#486 

Describe the solution you'd like
--------------------------------

Display message when log in through SteamID succeeds but is not associated with an admin.

Describe alternatives you've considered
---------------------------------------

n/a

Additional context
------------------

n/a

**Comment by rumblefrog** [comment]
I believe it's intended and it's best for it to be hidden to dissuade random users. I'd like to hear people's take on this.

At the least case, we can enable it only if debug mode is also enabled.

**Comment by Groruk** [comment]
You could probably get away with "Login successful, but you are not an admin". That shouldn't disclose much gatherable information.

Any other error would probably result in a generic "Unable to login with steam" error since the openid library is probably designed to return false or null on errors instead of throwing errors or exceptions to disclose as little information as possible.

**Comment by geominorai** [comment]
A debug mode would be useful.  Sometimes I login successfully via the Steam sign-in button but it still shows me as not logged in after being redirected to the SB main page.  Not sure if it's related to what's causing #374 though.
