### ISSUE TITLE
Cant setup sourcebans with nginx ?

### ISSUE THREAD

**Issue by m333w** [sbpp/sourcebans-pp#543]
Hi all, 

Anyone can share me a nginx vhost ? Mine dont work : https://pastebin.com/zsCtnW5U

Best regards.

**Comment by Groruk** [comment]
Since this issue isn't directly related to SourceBans++ and is more focused on NGINX, 
the [SourceBans++ Discord](https://discord.gg/4Bhj6NU) would be a better way to find help. (Issues on GitHub should be more or less directly related to SourceBans++ and its modules)

Additionally there is a [support option offered by NGINX directly](https://www.nginx.com/support/) and the massive [NGINX Documentation](https://docs.nginx.com/nginx/admin-guide/) that should help with configuration.

**Comment by m333w** [comment]
Well ok, i am @NOT-FOUND on discord, do you run sb on nginx ? Can you share your vhost on discord ?

Best regards.

**Comment by m333w** [comment]
solved with @bara on discord. Thx to him. 

If someone want add the vhost to the documentation for nginx with php7.2 : https://pastebin.com/JmQ3KCh4

**Comment by Bara** [comment]
https://pastebin.com/4Gmbd4e9
Here's a another version with more ssl stuff (that should get an A+ rating on [ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=csgottt.com)).

I use an pretty comparable version with nginx 1.15.6 and php 7.3 and works fine here.

**Comment by m333w** [comment]
@Bara i have remove and edit thoes line to be working with "any" nginx. Got cliper.conf for that and ssl.conf
