### ISSUE TITLE
SB 1.6.3 - Connection Error from Web to Gameserver

### ISSUE THREAD

**Issue by ChaosToaster** [sbpp/sourcebans-pp#557]
Hello Guys,

i have a Problem with the Installation of Sourcebans. we Used the newest Version of SB and after a Fresh CSGO Server Installation we install SB. First on Gameserver, than on the Webserver. After that, i see in the SB Webpanel the following Messge:
Error Connection (88.99.105.93:28015)

After that i go in the Web and search the error and found a Topic where the guys say ist better if i run the following file:
sb_debug_connection

after that i got this Message:

```
[+]SourceBans "Error Connecting()" Debug starting for server 88.99.105.93:28615

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[-] Error getting server info. Can't read from UDP stream. Port is possibly blocked.

[+] Trying to establish TCP connection
[-] Error connecting #111: Connection refused
```

In Server log i found this

`L 02/03/2019 - 01:36:25: [sbpp_comms.smx] You must set valid `ServerID` value in sourcebans.cfg!`

View in the Webpanel: http://prntscr.com/mfw1ow

I dont know what is the Problem cause the Database works and i see tables from SB. The Webserver ist worked too and fsock is open. I use my root and webserver for a Long time and have never Problems os it. I run many years different Server without Problems.

Server IP is: 88.99.105.93:28615
Maybe somebody have an Idea

What versions of software are you using?
----------------------------------------
**Operating System: Linux Debian
**SourceBans: 1.6.3
**SourceMod Version: newest
**MetaMod Version: newest

**Comment by Groruk** [comment]
https://forums.alliedmods.net/showpost.php?p=2637880&postcount=1351
This post already answers your problems, but okay.

> [-] Error getting server info. Can't read from UDP stream. Port is possibly blocked.

> [-] Error connecting #111: Connection refused

Both those outputs confirm that UDP and TCP traffic are blocked somewhere (presumably by a firewall).
And a quick double check confirms that the server is pingable from a different source.
![capture](https://user-images.githubusercontent.com/5796460/52172337-ada98f80-276d-11e9-87c5-11cd18eefab3.PNG)

Which leads us to the conclusion that your webserver is blocking the connection and you should check the firewall of the webserver and make sure that both UDP and TCP traffic are open for the server port (`28615`)

---

>In Server log i found this
>L 02/03/2019 - 01:36:25: [sbpp_comms.smx] You must set valid ServerID value in sourcebans.cfg!

Well, then you should set the ServerID in the sourcebans.cfg just as the log messsage is telling you to (more infos here: https://sbpp.github.io/docs/adding_server/#configuring-sourcebans-s-serverid)

---

> SourceMod Version: newest
> MetaMod Version: newest

In future issues you should specify the exact versions used and not just 'newest', because that could mean all sorts of different things (like newest stable release or newest dev release or are we talking about the newest 'nightly' builds straight from the github repos)
