### ISSUE TITLE
Add Admins Error with no password

### ISSUE THREAD

**Issue by distratul** [sbpp/sourcebans-pp#670]
What are the steps to reproduce this issue?
-------------------------------------------
1. When adding an admin with no web panel privileges it still requires  to putt a password.

![Untitled](https://user-images.githubusercontent.com/33494107/81439216-b2ca6b00-9176-11ea-9a92-b5312dc6717e.png)

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by Groruk** [comment]
Not a bug, passwords just like other login credentials (account name and steamid) are required regardless of the permissions set for the user, because every user should be able to log into the webpanel (because of this feature https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/configs/sourcebans/sourcebans.cfg#L43-L44 from the original SourceBans)
