### ISSUE TITLE
Error Connecting on webpanel server list

### ISSUE THREAD

**Issue by Catscz** [sbpp/sourcebans-pp#776]
What are the steps to reproduce this issue?
-------------------------------------------
1. I don't know
2.
3.
4.

What happens?
-------------
https://ctrlv.link/vBWD

What were you expecting to happen?
----------------------------------
To show name, map, capacity, etc.

Any logs, error output, etc.?
----------------------------

https://ctrlv.link/vBWD

Any other comments?
-------------------
Please help

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by Megamezzomixer** [comment]
I have the same problem.
I'm running this docker image: [https://github.com/crinis/sourcebans-docker](https://github.com/crinis/sourcebans-docker)
The only difference in the default setup is a different port, which then gets fed into a proxy host. Though the container has direct internet access, because the connection is bridged.

There also is no difference in accessing the webpage via url:port or the proxy host url, the server still shows as "Error Connecting".

**Comment by distratul** [comment]
The problem is maybe on your server host provider because it blocks some ports. If the problem is your, then delete the servers from the sourcebans (from admin panel) and put in sourcemod/configs/sourcebans/sourcebans.cfg to autoadd server then restart.

**Comment by alfari24** [comment]
I have done as you suggested, the ip has been automatically added to the sourcebans on the website, but still the connection error
