### ISSUE TITLE
[Comms] Valid user are sometime flase flagged

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#870]
What are the steps to reproduce this issue?
-------------------------------------------
1. Connect on your server
2. Sometimes you can't comms someone bcs it's return as `g_bPlayerStatus[target] = false;`

What happens?
-------------
![image](https://user-images.githubusercontent.com/11679883/224485906-d33b83fe-b229-41bd-bfb0-fae8e227c1c3.png)

What were you expecting to happen?
----------------------------------
Don't have false flag detection for `g_bPlayerStatus`

Any logs, error output, etc.?
----------------------------

N/A

Any other comments?
-------------------
Issue was found by Metric#0062

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 20.04
**SourceBans++ Version:** 1.8.0
**SourceMod Version:** 1.11 
**MetaMod Version:** 1.11

**Comment by ashgts** [comment]
I got same issue when i tried to mute myself, i was always getting this message, but this was excatly due to:

sbpp_comms.sp line 2249:
`if (strncmp(auth[6], "ID_", 3) != 0 )`

Should be:
`if (strncmp(auth[6], "ID_", 3) != -1)`

strncmp returns -1 when string not found. But okay this PR fixes it anyway.
