### ISSUE TITLE
[SourceSleuth] Duplicate account AUTO BAN

### ISSUE THREAD

**Issue by lugaamn** [sbpp/sourcebans-pp#918]
What are the steps to reproduce this issue?
-------------------------------------------
1.After I banned someone, I made it impossible for anyone else from that IP address to enter. The person who enters after that is automatically banned.
2. Banned Reason Duplicate account
3. Its not duplicated account 
4. Its just same ip address

What versions of software are you using?
----------------------------------------
Operating System: Linux
SourceBans++ Version: Latest stable
SourceMod Version: Latest stable
MetaMod Version: Latest stable

**Comment by Ferks-FK** [comment]
If it's the same IP address, the plugin assumes it's a duplicate account.

**Comment by lugaamn** [comment]
sourcebens 1.6.4 did not ban like this. How to stop this?

**Comment by lugaamn** [comment]
[https://imgur.com/a/9u5R00N](url)

**Comment by Ferks-FK** [comment]
Sourcebans has always done this.

**Comment by Nerus87** [comment]
It is because of checking both SteamId and public/external IP Addresses at the same time, It is good because you will ban smurfs.
But from the other side, I had situations where some guy get a ban, and a couple of years later another/different player have the same IP Address and cannot join the server (I propose excluding SteamId from IP for this specific example, but they don't want to do it).
